// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brand': string;
  'button-wrapper': string;
  'card': string;
  'card__title': string;
  'mobile-logo': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
