// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rooms-list': string;
  'rooms-list__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
