// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lights-list': string;
  'lights-list__btn-group': string;
  'lights-list__item': string;
  'lights-list__title': string;
}
export const cssExports: CssExports;
export default cssExports;
