// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'thermostat': string;
  'thermostat__controls': string;
  'thermostat__label': string;
}
export const cssExports: CssExports;
export default cssExports;
